#ifndef VOXHAUT_VOICE_PLAYER_DEFS_H
#define VOXHAUT_VOICE_PLAYER_DEFS_H

#define VOX_SYNTH_NUM 100

#define VOX_SYNTH_HELLO VOX_SYNTH_NUM + 1
#define VOX_SYNTH_HUMIDITY VOX_SYNTH_NUM + 2
#define VOX_SYNTH_TEMP VOX_SYNTH_NUM + 3
#define VOX_SYNTH_SONG VOX_SYNTH_NUM + 4

#endif