#ifndef VOXHAUT_CONFIG_H
#define VOXHAUT_CONFIG_H

#define VOXHAUT_SERVER_SSID "VoxHAUT"
#define VOXHAUT_SERVER_PASSWORD "jograt_911"

#define VOXHAUT_SERVER_PORT 80
#define VOXHAUT_SERVER_LOCAL_IP 192, 168, 1, 1
#define VOXHAUT_SERVER_SUBNET 255, 255, 255, 0
#define VOXHAUT_SERVER_GATEWAY VOXHAUT_SERVER_LOCAL_IP

#define VOXHAUT_ULTRASONIC_SENSOR_TRIGGER_PIN D5
#define VOXHAUT_ULTRASONIC_SENSOR_ECHO_PIN D6

#define VOXHAUT_MOTOR_1A 0
#define VOXHAUT_MOTOR_1B 0
#define VOXHAUT_MOTOR_2A 0
#define VOXHAUT_MOTOR_2B 0

#endif